const translations = {
  en: {
    appTitle: "CLUB Scheduler",
    home: "Home",
    language: "Language",
    players: "Players",
    rounds: "Rounds",
    summary: "Summary",
    fontSize: "Font Size",
    reset: "Reset",
    resetAll: "Reset App",
    resetExcept: "Reset Games",
    enterCourts: "Enter Number of Courts",
    importPlayers: "Import Multiple Players ▶",
    gender: "Gender",
    male: "Male",
    female: "Female",
    import: "Import",
    cancel: "Cancel",
    enterPlayerName: "Enter Player Name",
    addPlayer: "Add Player",
    fixedPairs: "Set Fixed Pairs (Optional)",
    add: "Add",
    pround: " Round",
    nround: "Next Round ",
    endrounds: "End Session ",
    roundno: "Round ",
    roundShort: "R",
    rank: "Rank",
    name: "Name",
    played: "Played",
    rested: "Rested",
    importExample: "Name,Gender\nKari,Male\nBhavani,Female",
    Timer: "Timer",
    min: "min",
    selectPlayer1: "Select Player 1",
    selectPlayer2: "Select Player 2",
    small: "Small",
    medium: "Medium",
    large: "Large",
    maxcourts: "Enter Number of Courts",
    sittingOut: "Resting",
    courts: "Courts",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    export: "Export",
    exporthtml: "📄 Export Summary",
    help: "Help",
    confirmResetAll: "Do you want to reset everything?",
    confirmResetGames: "Do you want to reset games only?",
    endRoundsConfirm: "Do you want to end the rounds?",
    yes: "Yes"
   
  },
  
  jp: {
    appTitle: "CLUB Scheduler",
    home: "ホーム",
    players: "選手一覧",
    rounds: "試合ラウンド",
    summary: "集計",
    language: "言語",
    fontSize: "文字サイズ",
    reset: "リセット",
    resetAll: "全てをリセット",
    resetExcept: "プレーヤー以外をリセット",
    enterCourts: "コート数を入力",
    importPlayers: "複数選手を取り込み  ▶",
    gender: "性別",
    male: "男",
    female: "女",
    import: "取り込み",
    cancel: "キャンセル",
    enterPlayerName: "選手名を入力",
    addPlayer: "選手追加",
    fixedPairs: "固定ペア設定（任意）",
    add: "追加",
    pround: " ラウンド",
    nround: "ラウンド ",
    endrounds: "終了する ",
    roundno: "ラウンド ",
    roundShort: "R",
    rank: "順位",
    name: "名前",
    played: "試合数",
    rested: "休憩数",
    importExample: "名前,性別\nカリ,男\nババニ,女",
    Timer: "タイマー",
    min: "分",
    selectPlayer1: "プレーヤー1を選択",
    selectPlayer2: "プレーヤー2を選択",
    small: "小",
    medium: "中",
    large: "大",
    maxcourts: "コートの数を入力してください",
    sittingOut: "休憩中:",
    courts: "コート",
    theme: "テーマ",
    light: "ライト",
    dark: "ダーク",
    export: "エクスポート",
    exporthtml: "📄 概要出力",
    
    confirmResetAll: "すべてをリセットしますか？",
    confirmResetGames: "試合のみをリセットしますか？",
    endRoundsConfirm: "ラウンドを終了しますか？",
    yes: "はい",
    help: "ヘルプ"

  },
  
  kr: {
  appTitle: "CLUB Scheduler",
  home: "홈",
  players: "선수",
  rounds: "라운드",
  summary: "요약",
  language: "언어",
  fontSize: "글자 크기",
  reset: "초기화",
  resetAll: "전체 초기화",
  resetExcept: "경기만 초기화",
  enterCourts: "코트 수 입력",
  importPlayers: "여러 선수 가져오기  ▶",
  gender: "성별",
  male: "남성",
  female: "여성",
  import: "가져오기",
  cancel: "취소",
  enterPlayerName: "선수 이름 입력",
  addPlayer: "선수 추가",
  fixedPairs: "고정 페어 설정 (선택)",
  add: "추가",
  pround: " 라운드",
  nround: "라운드 ",
  endrounds: "종료하기 ",  
  roundno: "라운드 ",  
  roundShort: "R",
  rank: "순위",
  name: "이름",
  played: "경기 수",
  rested: "휴식 수",
  importExample: "이름,성별\n카리,남성\n바바니,여성",
  Timer: "타이머",
  min: "분",
  selectPlayer1: "선수 1 선택",
  selectPlayer2: "선수 2 선택",
  small: "작게",
  medium: "보통",
  large: "크게",
  maxcourts: "코트 수를 입력하세요",
  sittingOut: "휴식 중:",
  courts: "코트",
  theme: "테마",
  light: "라이트",
  dark: "다크",
  export: "내보내기",
  exporthtml: "📄 요약 내보내기",
  
  confirmResetAll: "모든 데이터를 초기화하시겠습니까?",
  confirmResetGames: "경기만 초기화하시겠습니까?",
  endRoundsConfirm: "라운드를 종료하시겠습니까?",
  yes: "확인",
  help: "도움말"
},
  
vi: {
  appTitle: "CLUB Scheduler",
  home: "Trang chủ",
  players: "Người chơi",
  rounds: "Vòng đấu",
  summary: "Tóm tắt",
  language: "Ngôn ngữ",
  fontSize: "Cỡ chữ",
  reset: "Đặt lại",
  resetAll: "Đặt lại tất cả",
  resetExcept: "Đặt lại trận đấu",
  enterCourts: "Nhập số sân",
  importPlayers: "Nhập nhiều người chơi  ▶",
  gender: "Giới tính",
  male: "Nam",
  female: "Nữ",
  import: "Nhập",
  cancel: "Hủy",
  enterPlayerName: "Nhập tên người chơi",
  addPlayer: "Thêm người chơi",
  fixedPairs: "Cố định cặp đấu (Tùy chọn)",
  add: "Thêm",
  pround: " Vòng",
  nround: "Vòng ",
  endrounds: "Kết thúc phiên ",  
  roundno: "Vòng ",
  roundShort: "R",
  rank: "Xếp hạng",
  name: "Tên",
  played: "Số trận",
  rested: "Số lần nghỉ",
  importExample: "Tên,Giới tính\nKari,Nam\nBhavani,Nữ",
  Timer: "Hẹn giờ",
  min: "phút",
  selectPlayer1: "Chọn người chơi 1",
  selectPlayer2: "Chọn người chơi 2",
  small: "Nhỏ",
  medium: "Vừa",
  large: "Lớn",
  maxcourts: "Nhập số sân",
  sittingOut: "Đang nghỉ:",
  courts: "Sân",
  theme: "Chủ đề",
  light: "Sáng",
  dark: "Tối",
  export: "Xuất",
  exporthtml: "📄 Xuất bản tóm tắt",
  
  confirmResetAll: "Bạn có muốn đặt lại tất cả không?",
  confirmResetGames: "Bạn có muốn đặt lại trận đấu không?",
  endRoundsConfirm: "Bạn có muốn kết thúc các vòng không?",
  yes: "Có",
  help: "Trợ giúp"
},
  
zh: {
  appTitle: "CLUB 调度器",
  home: "首页",
  players: "球员",
  rounds: "回合",
  summary: "汇总",
  language: "语言",
  fontSize: "字体大小",
  reset: "重置",
  resetAll: "重置应用",
  resetExcept: "仅重置比赛",
  enterCourts: "输入场地数量",
  importPlayers: "导入多个球员 ▶",
  gender: "性别",
  male: "男",
  female: "女",
  import: "导入",
  cancel: "取消",
  enterPlayerName: "输入球员姓名",
  addPlayer: "添加球员",
  fixedPairs: "设置固定搭档（可选）",
  add: "添加",
  pround: " 回合",
  nround: "回合 ",
  endrounds: "结束会话 ",  
  roundno: "回合 ",
  roundShort: "R",
  rank: "排名",
  name: "姓名",
  played: "已比赛",
  rested: "休息次数",
  importExample: "姓名,性别\nKari,男\nBhavani,女",
  Timer: "计时器",
  min: "分钟",
  selectPlayer1: "选择球员 1",
  selectPlayer2: "选择球员 2",
  small: "小",
  medium: "中",
  large: "大",
  maxcourts: "请输入场地数量",
  sittingOut: "休息中:",
  courts: "场地",
  theme: "主题",
  light: "浅色",
  dark: "深色",
  export: "导出",
  exporthtml: "📄 导出汇总",
  
  confirmResetAll: "确定要重置所有内容吗？",
  confirmResetGames: "确定只重置比赛吗？",
  endRoundsConfirm: "确定要结束回合吗？",
  yes: "确定",
  help: "帮助"
}
  
  
  
};
